# Site settings
title: Gjergj Sheldija
header-img: img/home-bg.jpg
email: gjergj@sheldija.net
copyright_name: Gjergj Sheldija 
description: "Blog and website of Gjergj Sheldija, blogging mainly for tech. Opinions expressed are mine."
baseurl: ""
url: "https://gjergjsheldija.github.io"
twitter_username: gjergj_sheldija
github_username:  gjergjsheldija
# facebook_username:  StartBootstrap
email_username:  gjergj@sheldija.net
linkedin_username: gjergjsheldija

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id:

# Disqus Comments
disqus:
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
shortname: codesauceblog

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
